# site settings
title: African Green Growth Development Forum
subtitle: (AGDF)
email: info@agdf.eco
# description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 10 Oma Street, Off IBB Way
city: Calabar
state: Cross River State
# zip_code: 55555
country: Nigeria
# phone: (716) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 0

# social settings
# 500px_url:
# facebook_url:
# github_url:
# gitlab_url: https://gitlab.com/andrewbanchich
# googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
# instagram_url: https://instagram.com
# linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
# pinterest_url:
# slack_url:
# twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
